In [3]:
!pip3 install torch torchvision torchaudio

     ---------------------------------------- 1.2/1.2 MB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 2.4/2.4 MB 4.7 MB/s eta 0:00:00
     -------------------------------------- 198.6/198.6 MB 3.4 MB/s eta 0:00:00
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1
    Uninstalling torch-1.12.1:
      Successfully uninstalled torch-1.12.1


In [4]:
## checking the version
import torch
torch.__version__

'2.2.1+cpu'

### Creating tensors

In [5]:
## Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [9]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
## Checking dimension
vector.ndim

1

In [11]:
## Check shape of vector
vector.shape

torch.Size([2])

- Vector has 2 elements

In [13]:
## Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
## Dimensions
MATRIX.ndim

2

In [15]:
## shape
MATRIX.shape

torch.Size([2, 2])

In [16]:
## tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9,],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
## Checking dimensions
TENSOR.ndim

3

In [18]:
## shape of the TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.shape

(tensor([[0.4399, 0.5874, 0.2539, 0.6648],
         [0.9044, 0.0738, 0.3511, 0.7585],
         [0.4339, 0.2650, 0.5035, 0.0328]]),
 torch.Size([3, 4]))

In [21]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros.shape

torch.Size([3, 4])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.shape,ones.ndim

(torch.Size([3, 4]), 2)

In [27]:
## torch.arange()
zero_to_ten_depercated = torch.range(0,10)
zero_to_ten_depercated

C:\Users\Prince\AppData\Local\Temp\ipykernel_19044\1883074648.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_depercated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype  = None, # defaults to None, which is torch.float32 or whatever datatype is passed
                              device = None, # defaults to None, which uses the default tensor type
                              requires_grad = False)# if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = torch.float16)  ##torch.half would also work
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [34]:
## Creat a tensor
some_tensor = torch.rand(3,4)

## Find out details about it
print(some_tensor)
print(f'Shape of tensor:{some_tensor.shape}')
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Device tensor is stored on:{some_tensor.device}')

tensor([[0.8777, 0.8421, 0.1223, 0.8569],
        [0.3424, 0.1491, 0.5744, 0.7177],
        [0.2274, 0.0553, 0.8029, 0.4219]])
Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


### Manipulating tensors (tensor operations)

#### Basic operations

In [35]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [36]:
# Multiply it by 10
tensor*10

tensor([10, 20, 30])

In [37]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [38]:
# Subtract and reassign
tensor = tensor-10
tensor

tensor([-9, -8, -7])

In [39]:
# Add and reassign
tensor = tensor+10
tensor

tensor([1, 2, 3])

In [40]:
# Can also use torch functions
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [41]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [42]:
## alternative
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor,'*',tensor)
print('Equals:',tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

`@` in Python is the symbol for matrix multiplication.

In [45]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [46]:
# Element-wise matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [47]:
# Matrix multiplication
tensor@tensor

tensor(14)

In [52]:
## other way
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
import timeit

In [64]:
## Checking out the time 
# %timeit sum(range(1000))
## Matrix multiplication by hand
%%time
value=0
for i in range(len(tensor)):
    value+= tensor[i]*tensor[i]
value

UsageError: Line magic function `%%time` not found.


In [56]:
tensor

tensor([1, 2, 3])

In [66]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [71]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]],dtype=torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]],dtype = torch.float32)
                         
torch.matmul(tensor_A,tensor_B)               

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [72]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [73]:
# View tensor_A,T and tensor_B.T
print(tensor_A.T)
print(tensor_B.T)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [75]:
# The operation works when tensor_B is transposed
print(f'Origianl shapes: tensor_A  = {tensor_A.shape},tensor_B:{tensor_B.shape}')
print(f'New shape: tensor_A={tensor_A.shape},tensor_B.T = {tensor_B.T.shape}' )
print(f'Multiplying:{tensor_A.shape}*{tensor_B.T.shape}')
print('Output')
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f'Output_shape:{output.shape}')

Origianl shapes: tensor_A  = torch.Size([3, 2]),tensor_B:torch.Size([3, 2])
New shape: tensor_A=torch.Size([3, 2]),tensor_B.T = torch.Size([2, 3])
Multiplying:torch.Size([3, 2])*torch.Size([2, 3])
Output
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output_shape:torch.Size([3, 3])


In [77]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A,tensor_B.T)
# tensor_A @tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

`torch.nn.Linear()` feed forward layer

In [84]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible 
torch.manual_seed(42)
## This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, ##matches inner dimensions of input
                        out_features=6) ## describes outer value
x  = tensor_A
output = linear(x)
print(f'Input_shape:{x.shape}\n')
print(f'Output:{output}\n\n Output shape:{output.shape}\n')

Input_shape:torch.Size([3, 2])

Output:tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

 Output shape:torch.Size([3, 6])



In [80]:
x.shape

torch.Size([3, 2])

In [86]:
## changing in_features from 2 to 3
linear = torch.nn.Linear(in_features=3,
                        out_features=6)
x = tensor_A.T
linear(x)

tensor([[ 3.4945,  0.8699, -3.4421,  0.6183,  1.9736, -0.8259],
        [ 4.5867,  1.0541, -4.0723,  0.4261,  2.5616, -0.7943]],
       grad_fn=<AddmmBackward0>)

### Finding the min, max, mean, sum, etc (aggregation)¶

In [87]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
print(f'Minimum:{x.min()}')
print(f"Maximum:{x.max()}")
# print(f"Mean:{x.mean()}")  will get an error
print(f"Mean:{x.type(torch.float32).mean()}") # won't work without float datatype
print(f'Sum:{x.sum()}')

Minimum:0
Maximum:90
Mean:45.0
Sum:450


In [92]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [101]:
## Torch methods
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

In [102]:
## create a tensor
tensor = torch.arange(0,100,10)
print(f"Tensor:{tensor}")

Tensor:tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [104]:
## Returns the index of min and max values
print(f'Index where max value occurs:{tensor.argmax()}')
print(f'Index where min value occurs:{tensor.argmin()}')

Index where max value occurs:9
Index where min value occurs:0


### Change tensor datatype

In [105]:
## Create a tensor and check its datatype
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [106]:
### Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [108]:
# Create a int8 tensor
torch_int8 = tensor.type(torch.int8)
torch_int8.dtype

torch.int8

### Reshaping, stacking, squeezing and unsqueezing