In [3]:
!pip3 install torch torchvision torchaudio

     ---------------------------------------- 1.2/1.2 MB 2.2 MB/s eta 0:00:00
     ---------------------------------------- 2.4/2.4 MB 4.7 MB/s eta 0:00:00
     -------------------------------------- 198.6/198.6 MB 3.4 MB/s eta 0:00:00
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
  Attempting uninstall: torch
    Found existing installation: torch 1.12.1
    Uninstalling torch-1.12.1:
      Successfully uninstalled torch-1.12.1


In [1]:
## checking the version
import torch
torch.__version__

'2.2.1+cpu'

### Creating tensors

In [5]:
## Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [9]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
## Checking dimension
vector.ndim

1

In [11]:
## Check shape of vector
vector.shape

torch.Size([2])

- Vector has 2 elements

In [13]:
## Matrix
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
## Dimensions
MATRIX.ndim

2

In [15]:
## shape
MATRIX.shape

torch.Size([2, 2])

In [16]:
## tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9,],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
## Checking dimensions
TENSOR.ndim

3

In [18]:
## shape of the TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.shape

(tensor([[0.4399, 0.5874, 0.2539, 0.6648],
         [0.9044, 0.0738, 0.3511, 0.7585],
         [0.4339, 0.2650, 0.5035, 0.0328]]),
 torch.Size([3, 4]))

In [21]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros.shape

torch.Size([3, 4])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.shape,ones.ndim

(torch.Size([3, 4]), 2)

In [27]:
## torch.arange()
zero_to_ten_depercated = torch.range(0,10)
zero_to_ten_depercated

C:\Users\Prince\AppData\Local\Temp\ipykernel_19044\1883074648.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_depercated = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [32]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype  = None, # defaults to None, which is torch.float32 or whatever datatype is passed
                              device = None, # defaults to None, which uses the default tensor type
                              requires_grad = False)# if True, operations performed on the tensor are recorded 
float_32_tensor.shape, float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [33]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = torch.float16)  ##torch.half would also work
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [34]:
## Creat a tensor
some_tensor = torch.rand(3,4)

## Find out details about it
print(some_tensor)
print(f'Shape of tensor:{some_tensor.shape}')
print(f'Datatype of tensor:{some_tensor.dtype}')
print(f'Device tensor is stored on:{some_tensor.device}')

tensor([[0.8777, 0.8421, 0.1223, 0.8569],
        [0.3424, 0.1491, 0.5744, 0.7177],
        [0.2274, 0.0553, 0.8029, 0.4219]])
Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


### Manipulating tensors (tensor operations)

#### Basic operations

In [35]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [36]:
# Multiply it by 10
tensor*10

tensor([10, 20, 30])

In [37]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [38]:
# Subtract and reassign
tensor = tensor-10
tensor

tensor([-9, -8, -7])

In [39]:
# Add and reassign
tensor = tensor+10
tensor

tensor([1, 2, 3])

In [40]:
# Can also use torch functions
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [41]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [42]:
## alternative
torch.mul(tensor,10)

tensor([10, 20, 30])

In [44]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor,'*',tensor)
print('Equals:',tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (is all you need)

`@` in Python is the symbol for matrix multiplication.

In [45]:
tensor = torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [46]:
# Element-wise matrix multiplication
tensor*tensor

tensor([1, 4, 9])

In [47]:
# Matrix multiplication
tensor@tensor

tensor(14)

In [52]:
## other way
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
import timeit

In [64]:
## Checking out the time 
# %timeit sum(range(1000))
## Matrix multiplication by hand
%%time
value=0
for i in range(len(tensor)):
    value+= tensor[i]*tensor[i]
value

UsageError: Line magic function `%%time` not found.


In [56]:
tensor

tensor([1, 2, 3])

In [66]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning (shape errors)

In [71]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]],dtype=torch.float32)

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]],dtype = torch.float32)
                         
torch.matmul(tensor_A,tensor_B)               

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [72]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [73]:
# View tensor_A,T and tensor_B.T
print(tensor_A.T)
print(tensor_B.T)

tensor([[1., 3., 5.],
        [2., 4., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [75]:
# The operation works when tensor_B is transposed
print(f'Origianl shapes: tensor_A  = {tensor_A.shape},tensor_B:{tensor_B.shape}')
print(f'New shape: tensor_A={tensor_A.shape},tensor_B.T = {tensor_B.T.shape}' )
print(f'Multiplying:{tensor_A.shape}*{tensor_B.T.shape}')
print('Output')
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f'Output_shape:{output.shape}')

Origianl shapes: tensor_A  = torch.Size([3, 2]),tensor_B:torch.Size([3, 2])
New shape: tensor_A=torch.Size([3, 2]),tensor_B.T = torch.Size([2, 3])
Multiplying:torch.Size([3, 2])*torch.Size([2, 3])
Output
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output_shape:torch.Size([3, 3])


In [77]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A,tensor_B.T)
# tensor_A @tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

`torch.nn.Linear()` feed forward layer

In [84]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible 
torch.manual_seed(42)
## This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, ##matches inner dimensions of input
                        out_features=6) ## describes outer value
x  = tensor_A
output = linear(x)
print(f'Input_shape:{x.shape}\n')
print(f'Output:{output}\n\n Output shape:{output.shape}\n')

Input_shape:torch.Size([3, 2])

Output:tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

 Output shape:torch.Size([3, 6])



In [80]:
x.shape

torch.Size([3, 2])

In [86]:
## changing in_features from 2 to 3
linear = torch.nn.Linear(in_features=3,
                        out_features=6)
x = tensor_A.T
linear(x)

tensor([[ 3.4945,  0.8699, -3.4421,  0.6183,  1.9736, -0.8259],
        [ 4.5867,  1.0541, -4.0723,  0.4261,  2.5616, -0.7943]],
       grad_fn=<AddmmBackward0>)

### Finding the min, max, mean, sum, etc (aggregation)¶

In [87]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [97]:
print(f'Minimum:{x.min()}')
print(f"Maximum:{x.max()}")
# print(f"Mean:{x.mean()}")  will get an error
print(f"Mean:{x.type(torch.float32).mean()}") # won't work without float datatype
print(f'Sum:{x.sum()}')

Minimum:0
Maximum:90
Mean:45.0
Sum:450


In [92]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [101]:
## Torch methods
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

In [102]:
## create a tensor
tensor = torch.arange(0,100,10)
print(f"Tensor:{tensor}")

Tensor:tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [104]:
## Returns the index of min and max values
print(f'Index where max value occurs:{tensor.argmax()}')
print(f'Index where min value occurs:{tensor.argmin()}')

Index where max value occurs:9
Index where min value occurs:0


### Change tensor datatype

In [105]:
## Create a tensor and check its datatype
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [106]:
### Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype

torch.float16

In [108]:
# Create a int8 tensor
torch_int8 = tensor.type(torch.int8)
torch_int8.dtype

torch.int8

### Reshaping, stacking, squeezing and unsqueezing

In [2]:
# Create a tensor
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [4]:
## Add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [5]:
# Change view (keeps same data as original but changes view)
z  =x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [6]:
### Chaning z will change x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [7]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [12]:
## squeeze operation
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)

tensor([5., 2., 3., 4., 5., 6., 7.])


In [13]:
x_squeezed.shape

torch.Size([7])

In [16]:
## unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed.shape)

torch.Size([1, 7])


In [17]:
## Create tensor with specific shape
x_original = torch.rand(size=(224,224,3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2,0,1)  ## shifts axis 0->1,1->2,2->0

print(f"Previous shape:{x_original.shape}")
print(f"Permuted shape:{x_permuted.shape}")

Previous shape:torch.Size([224, 224, 3])
Permuted shape:torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

In [2]:
## Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [21]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket:{x[0][0]}")
print(f"Third bracket:{x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:tensor([1, 2, 3])
Third bracket:1


In [22]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [28]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,:,2]

tensor([[3, 6, 9]])

In [5]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
x[:,0]

tensor([[1, 2, 3]])

In [6]:
x[:,:,1]

tensor([[2, 5, 8]])

In [7]:
x[:,1,1]

tensor([5])

In [8]:
x[0,0,:]

tensor([1, 2, 3])

In [11]:
x[0][0]

tensor([1, 2, 3])

In [12]:
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [13]:
print("x[0]:",x[0])

x[0]: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [14]:
print(x[0][0])

tensor([1, 2, 3])


In [15]:
print(x[0][1])

tensor([4, 5, 6])


In [16]:
print(x[0][2])

tensor([7, 8, 9])


In [17]:
x[:,0]

tensor([[1, 2, 3]])

In [18]:
x[:,1]

tensor([[4, 5, 6]])

In [19]:
x[:,2]

tensor([[7, 8, 9]])

In [20]:
x[:,:,1]

tensor([[2, 5, 8]])

In [21]:
x[:,:,0]

tensor([[1, 4, 7]])

In [23]:
x[:,:,2]

tensor([[3, 6, 9]])

In [25]:
x[:,1,0]

tensor([4])

In [27]:
x[:,1,1]

tensor([5])

In [28]:
x[0,0,:]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

In [30]:
import numpy as np
array  = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [34]:
tensor.type(dtype=torch.float32)

torch.float32

In [36]:
# Change the array, keep the tensor
array = array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [37]:
## Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [38]:
# Change the tensor, keep the array the same
tensor = tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Indexing practice

In [39]:
x = torch.arange(1,10).reshape(1,3,3)
x.shape

torch.Size([1, 3, 3])

In [41]:
x[:,0]

tensor([[1, 2, 3]])

In [44]:
x[:,:,1]

tensor([[2, 5, 8]])

In [45]:
x[:,1,1]

tensor([5])

In [46]:
x[0,0,:]

tensor([1, 2, 3])

### Reproducibility (trying to take the random out of random)

In [47]:
### Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A:\n{random_tensor_A}")
print(f"Tensor B:\n{random_tensor_B}")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2586, 0.1340, 0.8459, 0.5394],
        [0.8517, 0.8197, 0.4961, 0.5155],
        [0.7284, 0.7503, 0.3211, 0.9807]])
Tensor B:
tensor([[0.3148, 0.8821, 0.3028, 0.3952],
        [0.4775, 0.5584, 0.8839, 0.6126],
        [0.8778, 0.0111, 0.5232, 0.1685]])
Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [51]:
import random

## Set the random seed
RANDOM_SEED= 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n{random_tensor_C}")
print(f"Tensor D:\n{random_tensor_D}")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C ==  random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Running tensors on GPUs (and making faster computations)¶

In [52]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


### Exercises

### 2. Create a random tensor with shape (7, 7)

In [53]:
rand_tensor = torch.rand(7,7)

In [55]:
rand_tensor.shape

torch.Size([7, 7])

###  Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [56]:
rand_tensor_B = torch.rand(1,7)
## Matrix Multiplication
rand_tensor@rand_tensor.T

tensor([[2.9962, 2.0219, 1.9552, 2.7564, 2.7616, 1.6685, 2.6740],
        [2.0219, 1.5248, 1.5603, 1.8881, 1.9892, 1.1736, 1.9309],
        [1.9552, 1.5603, 2.1641, 1.9280, 2.1656, 1.5759, 2.0651],
        [2.7564, 1.8881, 1.9280, 2.6846, 2.7540, 1.4128, 2.4986],
        [2.7616, 1.9892, 2.1656, 2.7540, 3.2593, 1.7849, 2.7619],
        [1.6685, 1.1736, 1.5759, 1.4128, 1.7849, 1.8903, 1.8178],
        [2.6740, 1.9309, 2.0651, 2.4986, 2.7619, 1.8178, 2.6871]])

### Set the random seed to 0 and do 2 & 3 over again.

In [66]:
torch.random.manual_seed(0)
random_tensor_A = torch.rand(7,7)
# torch.random.manual_seed(0)
random_tensor_B = torch.rand(1,7)
random_tensor_A @random_tensor_B.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [67]:
random_tensor_A

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [68]:
random_tensor_B

tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

### Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [70]:
torch.cuda.manual_seed(1234)

### Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [71]:
## setting the seed
torch.manual_seed(1234)

## Check for access of gpu
device = "cuda" if torch.cuda.is_available() else "cpu"
device

## Create two random tensors on gpu
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A,tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

### Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [72]:
torch_C = torch.matmul(tensor_A,tensor_B.T)
torch_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### Find the maximum and minimum values of the output of 7


In [74]:
max = torch.max(torch_C)
min = torch.min(torch_C)
max,min

(tensor(0.5617), tensor(0.3647))

### Find the maximum and minimum index values of the output of 7

In [75]:
arg_max = torch.argmax(torch_C)
arg_min = torch.argmin(torch_C)
arg_max,arg_min

(tensor(3), tensor(0))

### Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [80]:
## set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1,1,1,10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D,tensor_D.shape)
print(tensor_E,tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
