In [3]:
!pip install tensorflow

     -------------------------------------- 300.9/300.9 MB 3.8 MB/s eta 0:00:00
     -------------------------------------- 413.4/413.4 kB 6.4 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 4.9 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 4.5 MB/s eta 0:00:00
     -------------------------------------- 133.7/133.7 kB 8.2 MB/s eta 0:00:00
     -------------------------------------- 938.6/938.6 kB 6.6 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 5.2 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     -------------------------------------- 442.0/442.0 kB 5.5 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 6.3 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 6.3 MB/s eta 0:00:00
     ------------------------------------- 186.9/186.9 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mysql-connector-python 8.1.0 requires protobuf<=4.21.12,>=4.21.1, but you have protobuf 4.25.3 which is incompatible.


In [6]:
import tensorflow as tf
import numpy as np

In [7]:
## check the current version of TensorFlow
print("Using TensorFlow version:", tf.__version__)

Using TensorFlow version: 2.15.0


### 1. Tensors of different Ranks

In [9]:
## A vector is a 1-dimensional tensor

##Vector in TensorFlow
vector_tf = tf.constant([0,1,2,3,4])

## Vector in numpy
vector_np = np.array([0,1,2,3,4])

print("Shapes:",vector_tf.shape,vector_np.shape)

Shapes: (5,) (5,)


In [12]:
## A matrix is a 2-dimensional array

# Matrix in TensorFlow
matrix_tf = tf.constant([[0,1],[2,3],[4,5]])

## Matrix in numpy
matrix_np = np.array([[0,1],[2,3],[4,5]])

print("Shapes:",matrix_tf.shape,matrix_np.shape)

Shapes: (3, 2) (3, 2)


In [14]:
## 3-dimension in tensorflow

t3_tf = tf.constant([[[0,1],[2,3],[4,5]]]*5)

# 3-d matrix in Numpy
t3_np = np.array([[[0,1],[2,3],[4,5]]]*5)

print("Shapes:",t3_tf.shape,t3_np.shape)

Shapes: (5, 3, 2) (5, 3, 2)


In [15]:
t3_tf

<tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])>

In [18]:
t3_tf2 = tf.constant([[[0.,1.],[2,3],[4,5]]]*5)
t3_tf2

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [19]:
t3_tf3 = tf.Variable([[[0.,1.],[2,3],[4,5]]]*5)
t3_tf3

<tf.Variable 'Variable:0' shape=(5, 3, 2) dtype=float32, numpy=
array([[[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [24]:
p = tf.constant([1,2,3])
p.shape
type(p)

tensorflow.python.framework.ops.EagerTensor

In [21]:
p.ndim

1

In [26]:
p = tf.constant()
q = tf.constant([1,3])
p = q+1

TypeError: constant() missing 1 required positional argument: 'value'

In [25]:
p = tf.constant()
p = [1,3]
p

TypeError: constant() missing 1 required positional argument: 'value'