In [3]:
!pip install tensorflow

     -------------------------------------- 300.9/300.9 MB 3.8 MB/s eta 0:00:00
     -------------------------------------- 413.4/413.4 kB 6.4 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 4.9 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 4.5 MB/s eta 0:00:00
     -------------------------------------- 133.7/133.7 kB 8.2 MB/s eta 0:00:00
     -------------------------------------- 938.6/938.6 kB 6.6 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 5.2 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB ? eta 0:00:00
     -------------------------------------- 442.0/442.0 kB 5.5 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 6.3 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 6.3 MB/s eta 0:00:00
     ------------------------------------- 186.9/186.9 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mysql-connector-python 8.1.0 requires protobuf<=4.21.12,>=4.21.1, but you have protobuf 4.25.3 which is incompatible.


In [14]:
import tensorflow as tf
import numpy as np

In [7]:
## check the current version of TensorFlow
print("Using TensorFlow version:", tf.__version__)

Using TensorFlow version: 2.15.0


### 1. Tensors of different Ranks

In [9]:
## A vector is a 1-dimensional tensor

##Vector in TensorFlow
vector_tf = tf.constant([0,1,2,3,4])

## Vector in numpy
vector_np = np.array([0,1,2,3,4])

print("Shapes:",vector_tf.shape,vector_np.shape)

Shapes: (5,) (5,)


In [12]:
## A matrix is a 2-dimensional array

# Matrix in TensorFlow
matrix_tf = tf.constant([[0,1],[2,3],[4,5]])

## Matrix in numpy
matrix_np = np.array([[0,1],[2,3],[4,5]])

print("Shapes:",matrix_tf.shape,matrix_np.shape)

Shapes: (3, 2) (3, 2)


In [14]:
## 3-dimension in tensorflow

t3_tf = tf.constant([[[0,1],[2,3],[4,5]]]*5)

# 3-d matrix in Numpy
t3_np = np.array([[[0,1],[2,3],[4,5]]]*5)

print("Shapes:",t3_tf.shape,t3_np.shape)

Shapes: (5, 3, 2) (5, 3, 2)


In [15]:
t3_tf

<tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [2, 3],
        [4, 5]]])>

In [18]:
t3_tf2 = tf.constant([[[0.,1.],[2,3],[4,5]]]*5)
t3_tf2

<tf.Tensor: shape=(5, 3, 2), dtype=float32, numpy=
array([[[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [19]:
t3_tf3 = tf.Variable([[[0.,1.],[2,3],[4,5]]]*5)
t3_tf3

<tf.Variable 'Variable:0' shape=(5, 3, 2) dtype=float32, numpy=
array([[[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]],

       [[0., 1.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [24]:
p = tf.constant([1,2,3])
p.shape
type(p)

tensorflow.python.framework.ops.EagerTensor

In [21]:
p.ndim

1

In [26]:
p = tf.constant()
q = tf.constant([1,3])
p = q+1

TypeError: constant() missing 1 required positional argument: 'value'

In [25]:
p = tf.constant()
p = [1,3]
p

TypeError: constant() missing 1 required positional argument: 'value'

### 2. Two ways of declaring tensors

In [3]:
#Two Types of tensors: tf.constant and tf.Variable
const_tensor = tf.constant([[1,2,3],[4,5,6]])
var_tensor = tf.Variable([[1,2,3],[4,5,6]])

In [4]:
## Declaring tensors with specific datatypes
int32_tensor = tf.Variable([[1,2,3],[4,5,6]],dtype=tf.int32)
float32_tensor = tf.Variable([[1,2,3],[4,5,6]],dtype = tf.float32)
bool_tensor = tf.Variable([True,False,False],dtype=tf.bool)

In [5]:
print("Int32 tensor:",int32_tensor)
print("Float32 tensor:",float32_tensor)
print("Boolean tensor:",bool_tensor)

Int32 tensor: <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
Float32 tensor: <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
Boolean tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False, False])>


In [6]:
## Contents of the tensor as a numpy array
int32_tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(int32_tensor)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [8]:
##tf.variable automatically infers the datatype
var = tf.Variable([True,False,False])
var

<tf.Variable 'Variable:0' shape=(3,) dtype=bool, numpy=array([ True, False, False])>

### Question:
- Declare a tensor of shape(2,2,2,2) with random numbers from normal distribution whose mean is 1 and the standard deviation is also 1.

In [13]:
# Approach 1 - initialize the nd array in Numpy and then use that to initialize the tensor.
arr  = np.random.randn(2,2,2,2)  ## returns random numbers from standard normal distribution -mean=0,std=1
print(arr.shape)
print(arr)

(2, 2, 2, 2)
[[[[ 0.66390264 -0.44666887]
   [-0.59764817  0.16094347]]

  [[-1.73054628 -0.61050163]
   [-1.22075675 -0.56248108]]]


 [[[ 0.052072    0.67538323]
   [ 1.7729418  -0.06037426]]

  [[ 0.70828325  0.91828843]
   [-1.23182624 -1.35601157]]]]


In [14]:
arr  = arr+1 ## adding 1 makes the random numbers from normal distribution where mean=1
## to change the standard deviation suppose 2.5 we would have to multiply it with that number
## arr = 2.5*(arr+1)
arr_tf = tf.constant(arr)
print(arr_tf)

tf.Tensor(
[[[[ 1.66390264  0.55333113]
   [ 0.40235183  1.16094347]]

  [[-0.73054628  0.38949837]
   [-0.22075675  0.43751892]]]


 [[[ 1.052072    1.67538323]
   [ 2.7729418   0.93962574]]

  [[ 1.70828325  1.91828843]
   [-0.23182624 -0.35601157]]]], shape=(2, 2, 2, 2), dtype=float64)


In [15]:
print(type(arr_tf.numpy()))

<class 'numpy.ndarray'>


In [16]:
## Approach 2- using random number generating functions from Tensorflow
arr_tf = tf.random.normal((2,2,2,2),mean=1,stddev=1,name="my_tensor")
print(arr_tf.shape)
print(arr_tf.numpy())

(2, 2, 2, 2)
[[[[ 0.402516    0.7272959 ]
   [ 1.2723261  -0.51415753]]

  [[ 2.8986485   0.91074634]
   [ 1.8850359   1.6823676 ]]]


 [[[ 0.7768822   0.23124278]
   [-0.50564706 -0.9303099 ]]

  [[ 1.6784348   0.4679376 ]
   [ 1.9728832   2.022736  ]]]]


### 3. Common mathematical operations on tensors

In [17]:
## Let us define two tensors
x  = tf.Variable([list(range(5))]*5)  ## 2D tensor of shape(5,5)
y = tf.Variable([list(range(5,10))]*5)  #2D tensor of shape(5,5)
print("x:",x)
print("y:",y)

x: <tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])>
y: <tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])>


In [21]:
### Simple mathematical operations two tensors
z = x+y  ## element-wise addition
print("z:",z)

w = x*y  ## element-wise multiplication
print("w:",w)  ## This is not matrix multiplication and only element wise mul

v = y/x  ## element-wise division does not raise exception for division by 0 as Tensorflow supports inf and NAN types
print("v:",v)

z: tf.Tensor(
[[ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]
 [ 5  7  9 11 13]], shape=(5, 5), dtype=int32)
w: tf.Tensor(
[[ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]
 [ 0  6 14 24 36]], shape=(5, 5), dtype=int32)
v: tf.Tensor(
[[       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]
 [       inf 6.         3.5        2.66666667 2.25      ]], shape=(5, 5), dtype=float64)


In [24]:
## Alternatively use Tensorflow functions for the mathematical operations
a = tf.add(x,y)
print(a==z)

b = tf.multiply(x,y)
print(b==w)

c = tf.divide(y,x)
print(c==v)

tf.Tensor(
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]], shape=(5, 5), dtype=bool)
tf.Tensor(
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]], shape=(5, 5), dtype=bool)
tf.Tensor(
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]], shape=(5, 5), dtype=bool)


### Note that element-wise operations do not work if tensors are of different shapes or cannot be broadcasted

In [25]:
## transpose of tensors
y = tf.Variable([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])
z = tf.transpose(y)

print("Before transpose:",y)
print("After transpose:",z)

Before transpose: <tf.Variable 'Variable:0' shape=(5, 3) dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])>
After transpose: tf.Tensor(
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]], shape=(3, 5), dtype=int32)


In [26]:
## Doing element wise operation
a = tf.add(y,z)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [5,3] vs. [3,5] [Op:AddV2] name: 

### Questions in the course

In [27]:
tensor1  = tf.random.uniform((2,2),minval=1,maxval=20,dtype=tf.int32)
print("Initial tensor:",tensor1.numpy())
tensor2 = tf.pow(tensor1,2)
print("Squared tensor = ",tensor2.numpy())

Initial tensor: [[ 3 12]
 [ 3  8]]
Squared tensor =  [[  9 144]
 [  9  64]]


In [28]:
tensor1 = tf.random.uniform((2,2),minval=1,maxval=20,dtype=tf.int32)
print("Initial tensor:",tensor1.numpy())
tensor2 = tensor1*tensor1
print("Squared tensor=",tensor2.numpy())

Initial tensor: [[ 4  6]
 [11 18]]
Squared tensor= [[ 16  36]
 [121 324]]


In [29]:
tensor1 = tf.random.uniform((2,2),minval=1,maxval=20)
print("Initial tensor:",tensor1.numpy())
tensor2 = tf.pow(tensor1,2)
print("Squared tensor=",tensor2.numpy())

Initial tensor: [[16.496908  9.973395]
 [ 4.905825  8.822855]]
Squared tensor= [[272.14798  99.46861]
 [ 24.06712  77.84277]]


In [30]:
tensor1 = tf.random.uniform((2,2),minval=1,maxval=20,dtype=tf.int32)
print("Initial tensor:",tensor1.numpy())
tensor2 = tf.multiply(tensor1,tensor1)
print("Squared tensor= ", tensor2.numpy())

Initial tensor: [[12 17]
 [11 11]]
Squared tensor=  [[144 289]
 [121 121]]


In [31]:
16.496908*16.496908

272.14797356046404

In [32]:
9.973395*9.973395

99.468607826025

In [33]:
t1 = tf.Variable([[2,3,4], [5,7,9], [1,6,3], [5,8,4]])
t2 = tf.Variable([[2,3,4,5], [5,7,9,4], [1,6,3,9]])
t3 = t1+t2
print(t3)

InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [4,3] vs. [3,4] [Op:AddV2] name: 

### 4. Linear algebra on tensors

In [34]:
## Matrix Multiplication
x = tf.Variable([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])
y = tf.Variable([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])

z = tf.linalg.matmul(x,y) # matrix multiplication between a (5,5) and (5,3) tensor
print("z:",z)

z: tf.Tensor(
[[ 90 100 110]
 [240 275 310]
 [390 450 510]
 [540 625 710]
 [690 800 910]], shape=(5, 3), dtype=int32)


- Note that tf.linalg.matmul raises exception if tensor shapes are incompatible for matrix multiplication.

In [35]:
## Matrix inverse
try:
    x = tf.Variable([[2,3],[2,2]])
    xinv = tf.linalg.inv(x)
    print("Inverse of x:",xinv)
except Exception as e:
    print("Exception raised while performing tensor inverse:\n",str(e))

Exception raised while performing tensor inverse:
 Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse] name: 


- The above exception occured because matrix inverse is allowed only for float datatypes (float16,float32 etc.). The try-except block is purposefully used to demonstrate this behaviour.

### Question:

- Solve the following system of linear equations using tensorflow.
- x+y+z+w = 13
- 2x + 3y -w = -1
- -3x + 4y + z+ 2w = 10
- x + 2y -z +w = 1
- Ans: x = 2, y=0, z=6,w=5

In [38]:
## Answer of above question
coeff = tf.Variable([[1,1,1,1],[2,3,0,-1],[-3,4,1,2],[1,2,-1,1]],dtype=tf.float32)
print("Coeff:",coeff)

Coeff: <tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  0., -1.],
       [-3.,  4.,  1.,  2.],
       [ 1.,  2., -1.,  1.]], dtype=float32)>


In [39]:
y = tf.Variable([[13],[-1],[10],[1]],dtype=tf.float32)
print("Output:",y)

Output: <tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[13.],
       [-1.],
       [10.],
       [ 1.]], dtype=float32)>


In [40]:
## Solution = inv(coeff)*y
inv_coeff = tf.linalg.inv(coeff)

print("Inverse of coeff matrix:",inv_coeff)

x_solution = tf.matmul(inv_coeff,y)
print(x_solution)

Inverse of coeff matrix: tf.Tensor(
[[ 2.77777791e-01  5.55555224e-02 -1.66666672e-01  1.11111104e-01]
 [-7.40740746e-02  1.85185164e-01  1.11111104e-01  3.70370336e-02]
 [ 4.62962925e-01  9.25926119e-02  5.55555634e-02 -4.81481493e-01]
 [ 3.33333343e-01 -3.33333343e-01 -9.93410776e-09  3.33333343e-01]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 2.0000000e+00]
 [-1.1920929e-07]
 [ 5.9999995e+00]
 [ 5.0000000e+00]], shape=(4, 1), dtype=float32)


In [46]:
x_solution.numpy()

array([[ 2.0000000e+00],
       [-1.1920929e-07],
       [ 5.9999995e+00],
       [ 5.0000000e+00]], dtype=float32)

In [63]:
## Question
x = tf.Variable([[0.2, 1, 0.5]])
w = tf.Variable([[0.5], [1] , [-1.2]])
b = tf.Variable([[0.01]])

In [67]:
a = tf.add(tf.matmul(x,w),b)
a

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.51]], dtype=float32)>

In [70]:
p = tf.sigmoid(a)
print(p.numpy()[0][0])

0.62480646
